# Generated by Django 5.0.7 on 2024-07-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_response_answer_text_remove_response_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Answer',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['text'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['title'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
